### ISSUE TITLE
Crash when fiddling around not knowing what I'm doing

### ISSUE THREAD

**Issue by luqui** [lamdu/lamdu#114]
Create new top level definition named `f`:

    f x = empty: x

Then in repl

    >>> f (1..10)

Then go back to definition of `f` and start deleting its code from the right

    f x = empty: [x]    <delete>
    f x = [empty: ]      <delete>

Kaboom!

    Main exiting due to exception: unexpected state at alpha-eq
    CallStack (from HasCallStack):
      error, called at src/Hyper/Type/AST/Scheme/AlphaEq.hs:84:19 in hypertypes-0.1.0.1-2svHfbWfh44AvqZh6x8bWa:Hyper.Type.AST.Scheme.AlphaEq

**Comment by ysangkok** [comment]
I could reproduce this.

**Comment by yairchu** [comment]
Thanks for reporting!

I had a bug in my alpha-eq check, to explain -
In the fixed version, "f' has a red underline, and if you navigate to it it shows that the type of "f" had changed since using it in the repl. This check is done by comparing its current type's equivalence to its type upon use.
All the efficient type inference and alpha-equality is somewhat tricky and I had a bug..
