### ISSUE TITLE
Haskell

### ISSUE THREAD

**Issue by GetContented** [lamdu/lamdu#42]
If you throw haskell away, aren't you throwing away a massive library of work that can be immediately used?

(Or, put alternatively, aren't you making things harder than they need to be?)

**Comment by timthelion** [comment]
@GetContented The Haskell code that has been written isn't very usefull anyways, because the Haskell eco-system is constantly broken. Actually, most of the bug reports filed against lambdu have to do with some dependency breaking and lambdu failing to build. But that is NOT the reason why lambdu doesn't use haskell directly. The reason is, that lamdu uses something like named records to pass arguments to functions rather than curry notation. That's one of the things that the authors are playing with in order to make things more visual and easy to understand. In lambdu, calling a function is a bit like filling out a form, and you know exactly what each field stands for.

**Comment by GetContented** [comment]
Yes, I actually should have further clarified that the thing I was talking about specifically wasn't the syntax... it was rather the symantics of the forms:  I was specifically talking about currying.

The problem with not supporting currying is that Lambdu would make pulling the components out more tricky... 

By currying here you're talking about basically accepting named function parameters, which is effectively taking a map (hashmap / associative array) as an argument rather than a single function. 

This has all sorts of issues.

Currying is actually one of the reasons Haskell is awesome. Coupled with laziness, this means you can do things you cannot do without it (like basically not needing macros when compared to Lisp).

It's also one of the reasons why Haskell ends up being quite fascinated by the shape of functions. All sorts of immutable truths crop up (like... combinators, etc).

This brings up another issue... the real reason that I asked this question... which is that the IDE could be decoupled from the language and therefore its representation, and storage (the thing I'm really interested in at the moment). Then building, say, a web interface on it would be trivial... or putting it on a server, etc. etc. (ie modularity).

I disagree with the "everything in Haskell is constantly broken" assertion.

'course, I could just be being naïve here...

**Comment by Peaker** [comment]
@GetContented Hey, we do intend to have good FFI support to gain access to large ecosystems.

We also don't believe Haskell is broken. Haskell is great! Evidently, we're using Haskell to implement Lamdu, we wouldn't do so if we believed Haskell sucked :)

However, Lamdu has different trade-offs:

* We believe that eager-by-default evaluation is a better basis for a programming language, when a smart UI can make explicit, typed laziness seamless and accessible.

* Currying is nice in the context of a textual language. In the context of Lamdu, though, eta-expanding everything to record-form can be well-hidden in the UI (Enjoying both the conciseness of currying, and the explicit naming of record fields).

* Making the editor fully modular is a very nice goal -- but we strive to create the best possible programming experience, which means we tailor both the language and the UI to one another in unison.

Language design is very much [affected](https://medium.com/lamdu-blog/designing-programming-languages-with-ides-in-mind-de890989dfa) by the IDEs the language is meant to be used with.
In light of this, making an IDE generic over programming languages necessarily loses a lot of the benefits.

Since we're eager by default, it is likely that FFI to a language like SML, OCaml, or even C++ would be easier to make effectively than FFI to Haskell.

**Comment by GetContented** [comment]
@Peaker Thanks for the detailed reply! I wonder, though, how you can get some of the best parts of Haskell into your language if there's no currying? Currying in the sense of the mathematics / lambda calculus definition of what a function is (a mapping from an input set to an output set)?

I agree that text is a broken UI for programming with. It's just no one has come up with a good way to get all the benefits of text with all the benefits of not having text yet. They either build a tedius UI, or a tedius amount of typing. Ironically programmers usually don't see large skads of their own repetition (but heartily advocate getting rid of it where they *do* see it).

Perhaps (as a PR-exercise) it might be pertinent to embellish http://peaker.github.io/lamdu/ with information about exactly how you can get all the benefits of currying without currying (which seems to be what the page is suggesting). It might be worth explaining what (you see) the benefits of currying are.

**Comment by Peaker** [comment]
@GetContented 
Currying is just the technique of having functions return functions instead of taking tuples or records of arguments. Lamdu functions are very much like Haskell functions (an algorithm that maps from an input set to an output set, with the usual partiality). Lamdu also does not explicitly ban currying. You can use currying, but Lamdu is not tailored to make that convenient.

I see the benefits of currying as: A) Concise partial application (e.g: `map (f 5) [1,2,3]`).  B) More point-free combinators can apply (Is this an actual advantage? In Lamdu it probably isn't, as type-driven completions make ad-hoc function applications/compositions a breeze).

When we have our hidden eta-expansion mechanism in place, we can create such a page :)

**Comment by GetContented** [comment]
How would you implement something like Functor or Foldable without currying? How do you implement partially applied functions implicitly without Currying?

I guess I'll have to wait until I see Lamdu more - or maybe you can direct me to a page to see where this ad-hoc function application is a breeze in it? :)

It seems the tradeoffs you're making are similar to the ones OCaml makes, aren't they? It might be a valuable PR-exercise to have a page on how Lamdu is different than OCaml in these respect?

I guess what I'm advocating or looking for is a page or two on exactly *how* it achieves, or will achieve - the promise in your readme: that it makes programming radically improved - especially with respect to Haskell, as in my experience Haskell already delivers: it improves programming vastly, but it has a pretty big learning curve... in fact, Haskell improves it past where most languages can even go, and to my understanding this is at least partially as a result of currying and laziness. I'm not sure how you can implement much of what makes Haskell amazing without them.

In particular, if arguments are eagerly evaluated, to get a lot of what Haskell provides "for free" with lazy argument evaluation, you'll need to implement a Lisp-like macro system, won't you? That, to me, seems like a massive problem.

**Comment by Peaker** [comment]
Functor can look something like:
`Functor f = forall a b. { fmap : { map : a -> b, val : f a } -> f b }`

If you want to partially apply fmap on just a map, then behind the scenes you have code like: `\x -> fmap { map=something, val=x }`, but the UI presents it as: `fmap {map=something}` with a visual cue that the braces represent a partial record -- that some args are missing. Note that you can also partially apply the val, not just the map.  In Haskell it is awkward (`flip fmap x`) but in Lamdu partial application appears with a name, instead.

Lamdu is similar to OCaml in some respects, to Smalltalk in others, and Haskell in yet others :)

Lamdu has laziness, it is just typed & (semi-)explicit. For example, when you implement the short-circuiting OR function, you implement it as something like:

```
(||) :: Bool -> (() -> Bool) -> Bool
True || x = True
False || x = x ()
```

With nice sugar (`◗`) for the `() -> a` construct (both the lambda and the type).

When you use `||`, you write: `x ||` and the auto-completion shows you `x ||◗ _`  so the second arg is lazy (and typed as such). You don't have to explicitly write the lazy suspension here, but you do see it as an explicit symbol right before your second argument.

I hope this makes it clear how Lamdu still can use laziness to avoid macros -- while being more explicit about it to avoid many of the downsides (unpredictability, performance issues, etc).

**Comment by GetContented** [comment]
Ok. Thanks for the long reply. Makes sense and highlights some of the issues that are common in Haskell (partially applying some portions of functions, for example).

**Comment by GetContented** [comment]
It's curious if the value isn't anonymous how you'd apply the fmapping across things that haven't been declared yet, but I guess when you're creating your Functor instance you haven to specify an implementation anyway, which could be where you're picking your explicit function name.

I wonder how it'd work for fmapping over (->) though? which argument do you pick? I guess you could choose. This seems like an inefficient way to learn about lamdu (which is why all my comments have been encouraging you to make more web pages explaining this stuff rather than replying to my individual questions ;-))
