### ISSUE TITLE
consider release process?

### ISSUE THREAD

**Issue by jbenet** [lamdu/lamdu#52]
Hey authors, fantastic project. excited :) -- so much "Yes!!!".

Would be nice if there were builds of lamdu, even just on the "github releases" page. 

bonus points:
- version changelog
- some release schedule (i recommend cutting a version from master every N weeks, way easier on you as you dont have to justify holding or making a release)

I dont care for this, but if you eventually want an osx installer, you can use template here: https://github.com/jbenet/data/tree/master/platforms/installers/osx (and i can contribute this if you want it, but idk if it is desired here)

**Comment by flacle** [comment]
@jbenet +1

**Comment by Peaker** [comment]
Please feel free to make a pull request, we'd love that :-)

**Comment by lovasoa** [comment]
What would be needed in a pull request ? There is nothing to add to the code.

**Comment by yairchu** [comment]
* We can start having version numbers and make a version changelog.
* One thing currently in the works, the new_schema branch, is data migrations - so that when we change the language old sessions can still be loaded, which will makes us a bit more mature, in a way more so than textual languages that rely on the users manually migrating such things via deprecation warnings etc.

Don't know about making a release schedule, the amount of work we can put it varies depending on work and other pressures.. But we can try to make a road-map :)

**Comment by yairchu** [comment]
I think we're soon ready to make a 0.1 release. Still need to [improve responsiveness when editing large functions](https://www.reddit.com/r/lamdu/comments/8o3kiu/weekly_progress_report_of_20180602/), and maybe do some more cleanups to be more contributor-friendly, and then make a release: macOS, Windows installers etc, and some nice intro videos :)

Still there would be very important stuff missing like UI to edit types (for now can add Nominal types via importing a sucky text/json format), type classes and higher order polymorphism.. But it's still enough to [make useful stuff](https://www.reddit.com/r/lamdu/comments/8gii55/dogfooding_report_web_site_for_iac2018/) working around the missing features.
I guess adding any of these would be a bump to 0.2, 0.3.. Also i18n (names for functions in stdlib available not just in English etc) would also be a nice 0.2 version bump. And I guess that when Lamdu will be self-hosted it should be version 1.0 :)

**Comment by yairchu** [comment]
Ok, here's the plan:

We're going to make a first release very soon. We've produced a nice video introducing Lamdu (which was also our LIVE 2018 Workshop submission), but we're delaying its release so that we also have our first release available when the video is.

The release process would be as follows:

* The release should have installers for macOS, Windows & Linux (we currently have problems to solve wrt the Windows build and making macOS installers). Btw @jbenet are you still interested in helping on macOS installers? :)
* When we do a X.Y.0, this is a feature release, and the "Bug research" column in [our tasks](https://trello.com/b/wojIVshY/lamdu) should be empty with all known bugs solved.
* In addition to tests and CI, we should do additional extensive manual tests before making a release.
* A minor release (i.e 0.7.0 => 0.7.1) should be a bugfix release.
* When an important feature is added the second number advances (i.e 0.7.1 => 0.8.0).
* When we reach an important milestone we'll advance the major version number (i.e 0.8.0 => 1.0.0)
* Git workflow: As we've done so far, the `master` branch stays the branch for cutting-edge development, with any unstable development happening on feature branches. When we make a feature release we will branch out a `stable` branch, and any bug-fixes will be cherry-picked to it, or from it to `master`, without doing merges between them.

The first release will be 0.7.0, where the 7 stands for a number of key features which we would like to highlight, which together make Lamdu what it is. Each of these took considerable effort and/or insight to achieve:

* WYTIWYS projectional editing. Projectional editing ensures that syntax errors and name errors are impossible to make, while the What-You-Type-Is-What-You-See text-like interface makes the experience intuitive and familiar. Note that this concept isn't unique to Lamdu - [MPS](https://www.jetbrains.com/mps/) also implements a WYTIWYS approach.
* A novel UI framework for keyboard oriented editing of rich structured data, with responsive layout (the code's layout adapts to the screen or window's width) and animations for structural edits (making changes easier to follow).
* Live-reloading for pure computations. Lamdu employs a distinction between pure computations and effectful code, like [Haskell](http://haskell.org), and uses this distinction to enable safe live programming, which performs live-reloading only for pure computations, while requiring an explicit action to execute effectful programs.
* Live programming with value annotations displayed under subexpressions (rather than only a single REPL result). Note that [Flogo 2](https://llk.media.mit.edu/papers/archive/ch-phd.pdf) appears to be the first project to come up with this notation.
* A novel approach for type-errors: When filling a hole with a term with a mismatching type, it is wrapped in a "fragment" (aka non-empty hole), so that type inference keeps working continuously everywhere. Note that following Lamdu, [Hazel](http://hazel.org) has also adopted this solution.
* A novel decentralized solution for cross-module blame assignment for type errors. For every definition, Lamdu remembers the types for all of its dependencies. When a dependency's type changes, type inference still works with the saved type, with an "update" action offered for the type-mismatch.
* Projectional Syntax Sugar: **TODO: write good description for the feature :)**

(@Peaker let me know if I omitted a key feature and I'll edit the list and initial version number accordingly)

**Comment by yairchu** [comment]
We did our first release! So we can consider this done :)
As follow up we should document it in our docs. I guess we can do so when we make a release history page at the time of the second release.
